apiVersion: v1
kind: ConfigMap
metadata:
  name: my-microservice-config
  namespace: my-microservice
  labels:
    app: my-microservice
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  API_VERSION: "v1"
