apiVersion: v1
kind: Secret
metadata:
  name: my-microservice-secrets
  namespace: my-microservice
  labels:
    app: my-microservice
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bsb2NhbGhvc3Q6NTQzMi9kYg==
  redis-url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==
  jwt-secret: bXktc2VjcmV0LWp3dC1rZXk=
